FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY . .
RUN ls
RUN dotnet restore ./Capstone.API/Capstone.API.csproj
RUN dotnet publish ./Capstone.API/Capstone.API.csproj -c Release -o api

FROM mcr.microsoft.com/dotnet/aspnet:8.0
EXPOSE 8080
WORKDIR /api
COPY --from=build /app/api .
RUN ls
CMD ["./Capstone.API"]